---
- name: Check if flatpak is installed
  ansible.builtin.command: which flatpak
  changed_when: false
  failed_when: false
  register: flatpak_check

- name: Install Flatpak
  become: true
  ansible.builtin.apt:
    name: "flatpak"
    state: present
    update_cache: true
  when: flatpak_check.rc != 0

- name: Check if Flathub remote exists
  ansible.builtin.command: flatpak --user remote-list --columns=name
  register: remote_list
  changed_when: false
  check_mode: false

- name: Add Flathub repository (if not exists)
  ansible.builtin.command: >
    flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  when: "'flathub' not in remote_list.stdout"
  register: add_flathub
  changed_when: true

- name: Include add_to_path role
  ansible.builtin.include_role:
    name: add_to_path
  vars:
    add_to_path_path_directory: "~/.local/share/flatpak/exports/bin"
