---
- name: Install Heroic Launcher
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: com.heroicgameslauncher.hgl
    flatpak_user_install_flatpak_app_alias: heroic
