---
- name: Ensure path is sourced in bashrc
  ansible.builtin.blockinfile:
    path: "{{ shell_config }}"
    block: |
      . "{{ add_source_to_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Source {{ add_source_to_config_path }}"
    insertafter: EOF
    mode: "0644"
