- name: Import kde config
  ansible.builtin.include_role:
    name: add_dotfiles_from_repo
  vars:
    add_dotfiles_from_repo_dotfile_repo: https://github.com/CookieGigi/kdeconfig.git
    add_dotfiles_from_repo_dotfile_name: kdeconfig
    add_dotfiles_from_repo_dotfile_repo_dir: dotfiles
