---
- name: Ensure curl is installed (for installer)
  become: true
  ansible.builtin.apt:
    name: curl
    state: present

- name: Ensure /nix directory exists
  become: true
  ansible.builtin.file:
    path: /nix
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install Nix (user-space, no daemon)
  ansible.builtin.shell: "sh <(curl -L {{ nix_install_url }}) --no-daemon"
  args:
    creates: "{{ nix_profil_path }}"
    executable: /bin/bash

- name: Include add_source_to_config role
  ansible.builtin.include_role:
    name: add_source_to_config
  vars:
    add_source_to_config_path: "{{ nix_profil_path }}"

- name: Include source role
  ansible.builtin.include_role:
    name: source
  vars:
    source_path: "{{ nix_profil_path }}"
