---
- name: Setup nvim_python_dev configuration
  ansible.builtin.include_role:
    name: add_neovim_config
  vars:
    add_neovim_config_path: "{{ nvim_python_dev_config_path }}"
    add_neovim_config_appname: "{{ nvim_python_dev_appname }}"
    add_neovim_config_alias: "{{ nvim_python_dev_alias }}"
    add_neovim_config_repo: "{{ nvim_python_dev_repo }}"
