---
- name: Install Steam
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: com.valvesoftware.Steam
    flatpak_user_install_flatpak_app_alias: steam
