add_dotfiles_from_repo_dotfile_path: ~/.dotfiles
add_dotfiles_from_repo_dotfile_repo: https://github.com/yourusername/bashrc.git
add_dotfiles_from_repo_dotfile_name: .bashrc
add_dotfiles_from_repo_dotfile_repo_dir: dotfiles
