- name: Add alacritty config
  ansible.builtin.include_role:
    name: add_dotfiles_from_repo
  vars:
    add_dotfiles_from_repo_dotfile_repo: https://github.com/CookieGigi/alacritty_config.git
    add_dotfiles_from_repo_dotfile_name: alacritty
    add_dotfiles_from_repo_dotfile_repo_dir: dotfiles
