---
- name: Ensure {{ path }} is sourced in bashrc
  ansible.builtin.blockinfile:
    path: "{{ shell_config }}"
    block: |
      . "{{ path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Source {{ path }}"
    insertafter: EOF
    mode: "0644"
  notify: Source shell_config


