---
- name: Create main user
  ansible.builtin.include_role:
    name: add_user
  vars:
    add_user_username: "{{ ansible_user }}"
    add_user_usergroups: "sudo"

- name: Add SSH key
  ansible.builtin.include_role:
    name: add_ssh_key
  vars:
    add_ssh_key_username: "{{ ansible_user }}"
