---
- name: Install applications
  hosts: localhost
  tags: [app, applications]

  roles:
    - role: kde-connect
      tags: [app, connectivity]
    - role: obsidian
      tags: [app, productivity, notes]
    - role: heroic-launcher
      tags: [app, gaming]
    - role: librewolf
      tags: [app, browser, privacy]
    - role: proton-pass
      tags: [app, security, password-manager]
    - role: firefox
      tags: [app, browser]
