---
- name: Install applications
  hosts: localhost
  tags: [app, applications]
  gather_facts: yes

  roles:
    - role: kde-connect
      tags: [app, connectivity]
    - role: obsidian
      tags: [app, productivity, notes]
    - role: heroic-launcher
      tags: [app, gaming]
    - role: steam
      tags: [app, gaming]
    - role: librewolf
      tags: [app, browser, privacy]
    - role: proton-pass
      tags: [app, security, password-manager]
    - role: firefox
      tags: [app, browser]
    - role: darktable
      tags: [app, photography, image-editing]
    - role: exiftool
      tags: [app, photography, image-metadata]
    - role: inkscape
      tags: [app, graphics, vector-editing]
