---
- name: Install all basics
  hosts: localhost

  handlers:
    - name: Source shell_config
      shell: . "{{ shell_config }}"
      args:
        executable: /bin/bash
      changed_when: false     

  roles:
    - add_main_user
    - lazygit
    - neovim
    - role: add_alias
      vars:
        alias_name: "vi"
        alias_cmd: "nvim"
    - netstat
    - alacritty
    - role: tmux
