---
- name: Install all basics
  hosts: localhost

  roles:
    - add_main_user
    - zsh
    - lazygit
    - neovim
    # CLI Tools
    - ripgrep
    - fd
    - fzf
    - zoxide
    - bat
    - eza
    - gh
    - jq
    - yq
    - shellcheck
    - tree

    - role: add_alias
      vars:
        add_alias_alias_name: "vi"
        add_alias_alias_cmd: "nvim"
    - netstat
    - jetbrains_nerd_font
    - alacritty
    - role: tmux
    - role: tmux_catppuccin
