---
- name: Install all basics
  hosts: localhost

  handlers:
    - name: Source shell_config
      ansible.builtin.shell: source "{{ shell_config }}"
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: true

  roles:
    - add_main_user
    - zsh
    - lazygit
    - neovim
    - role: add_alias
      vars:
        add_alias_alias_name: "vi"
        add_alias_alias_cmd: "nvim"
    - netstat
    - jetbrains_nerd_font
    - alacritty
    - role: tmux
    - role: tmux_catppuccin
