---
- name: Install all config
  hosts: localhost
  tags: [config, configuration]

  roles:
    - role: kde_config
      tags: [config, kde, desktop]
    - role: alacritty_config
      tags: [config, terminal]
