---
- name: Install Neovim development configuration
  hosts: localhost
  tags: [neovim, config, dev]

  roles:
    - role: nvim_dev
      tags: [neovim, config, dev]
    - role: nvim_sh_dev
      tags: [neovim, config, dev, sh]
    - role: nvim_rust_dev
      tags: [neovim, config, dev, rust]
    - role: nvim_python_dev
      tags: [neovim, config, dev, python]

- name: Install Neovim production configuration
  hosts: localhost
  tags: [neovim, config, prod]

  roles:
    - role: nvim_prod
      tags: [neovim, config, prod]
