---
- name: Install librewolf
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: "{{ librewolf_package }}"
    flatpak_user_install_flatpak_app_alias: librewolf

- name: Ensure librewolf var path exists
  ansible.builtin.file:
    path: "{{ librewolf_var_path }}"
    state: directory
    mode: '0755'

- name: Copy librewolf.overrides.cfg to {{ librewolf_var_path }}
  ansible.builtin.copy:
    src: librewolf.overrides.cfg
    dest: "{{ librewolf_var_path }}/librewolf.overrides.cfg"
    owner: "{{ ansible_user }}"
    mode: '0644'
