shell_config: "{{ lookup('env', 'HOME') }}/.zshrc"
nix_profil_path: "{{ lookup('env', 'HOME') }}/.nix-profile/etc/profile.d/nix.sh"
dotfiles_path: "{{ lookup('env', 'HOME') }}/dotfiles"

# Daily update configuration
daily_flatpak_packages:
  - org.mozilla.firefox
  - io.gitlab.librewolf-community

daily_flatpak_scope: user
daily_apt_enabled: true
daily_nvidia_enabled: true
