---
- name: Install AI tools
  hosts: localhost
  tags: [ai, development]
  gather_facts: yes

  roles:
    - role: opencode
      tags: [ai, editor, dev]

    - role: mcp-server
      tags: [ai, mcp]

    - role: gemini_cli
      tags: [ai, cli, gemini]
