---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Generate SSH key for user
  ansible.builtin.openssh_keypair:
    path: /home/{{ username }}/.ssh/id_rsa
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'
    type: rsa
    size: 4096
    state: present
