---
- name: Install darktable
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: org.darktable.Darktable
    flatpak_user_install_flatpak_app_alias: darktable
