---
# Install packages via APT

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install packages via apt
  ansible.builtin.apt:
    name: "{{ unified_packages.apt }}"
    state: present
  become: true
