---
- name: Install Inkscape via Flatpak
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: "org.inkscape.Inkscape"
    flatpak_user_install_flatpak_app_alias: "inkscape"
