---
tmux_catppuccin_install_path: "{{ ansible_env.HOME }}/.config/tmux/plugins/catppuccin/tmux"
tmux_catppuccin_repo_url: "https://github.com/catppuccin/tmux.git"
tmux_catppuccin_version: "v2.1.3"
tmux_catppuccin_flavor: "macchiato"
tmux_catppuccin_window_status_style: "slanted"
