---
- name: Install firefox
  ansible.builtin.include_role:
    name: flatpak_user_install
  vars:
    flatpak_user_install_flatpak_app_id: org.mozilla.firefox
    flatpak_user_install_flatpak_app_alias: firefox
