---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ add_ssh_key_username }}/.ssh
    state: directory
    owner: "{{ add_ssh_key_username }}"
    group: "{{ add_ssh_key_username }}"
    mode: '0700'

- name: Generate SSH key for user
  community.crypto.openssh_keypair:
    path: /home/{{ add_ssh_key_username }}/.ssh/id_rsa
    owner: "{{ add_ssh_key_username }}"
    group: "{{ add_ssh_key_username }}"
    mode: '0600'
    type: rsa
    size: 4096
    state: present
